# Form implementation generated from reading ui file 'Ui/EODPanel.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from QtApp.Base import CFrame, CWidget, CPushButton
from QtApp.Base.EditBox import eValueType, EditBox


class CEODPanelBase(CFrame):
    def __init__(self, aParent=None):
        CFrame.__init__(self, aParent)
        self.setupUi()

    def setupUi(self):
        self.setObjectName("EODPanel")
        self.MainLayout = QtWidgets.QVBoxLayout(self)
        self.BtnConfirm = CPushButton(self)
        self.BtnConfirm.setObjectName("BtnConfirm")
        self.BtnReset = CPushButton(self)
        self.BtnReset.setObjectName("BtnReset")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        _translate = QtCore.QCoreApplication.translate
        self.Values = {}
        for i in [50, 20, 10, 5, 2, 1, 0.5, 0.1, 0.05, 0.02, 0.01]:
            label = QtWidgets.QLabel(self)
            label.setObjectName(f"label{i}")
            if i >= 1:
                label.setText(_translate("Form", f"£{i} 数量"))
            else:
                label.setText(_translate("Form", f"{round(i * 100)}p 数量"))
            ValueBox = EditBox(self, eValueType.Int)
            ValueBox.setMinimum(0)
            Row = len(self.Values) // 3
            if len(self.Values) % 3 == 0:
                self.formLayout.setWidget(Row, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
                self.formLayout.setWidget(Row, QtWidgets.QFormLayout.ItemRole.FieldRole, ValueBox)
            elif len(self.Values) % 3 == 1:
                self.formLayout_2.setWidget(Row, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
                self.formLayout_2.setWidget(Row, QtWidgets.QFormLayout.ItemRole.FieldRole, ValueBox)
            else:
                self.formLayout_3.setWidget(Row, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
                self.formLayout_3.setWidget(Row, QtWidgets.QFormLayout.ItemRole.FieldRole, ValueBox)
            self.Values[i] = ValueBox

        self.formLayout_3.setWidget(Row, QtWidgets.QFormLayout.ItemRole.LabelRole, QtWidgets.QLabel(self))
        Row = len(self.Values) // 3 + 1
        label = QtWidgets.QLabel(self)
        label.setObjectName("label")
        label.setText(_translate("Form", "今日总现金收入"))
        self.LBTodayTotalCash = QtWidgets.QLabel(self)
        self.LBTodayTotalCash.setObjectName("label")
        self.LBTodayTotalCash.setText(_translate("Form", "0"))
        self.formLayout.setWidget(Row, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
        self.formLayout.setWidget(Row, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LBTodayTotalCash)

        label = QtWidgets.QLabel(self)
        label.setObjectName("label")
        label.setText(_translate("Form", "今日钱箱现金取出"))
        self.EditMoneyOut = EditBox(self, eValueType.Float)
        self.EditMoneyOut.setObjectName("EditMoneyOut")
        self.EditMoneyOut.setText('0')
        self.formLayout_2.setWidget(Row, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
        self.formLayout_2.setWidget(Row, QtWidgets.QFormLayout.ItemRole.FieldRole, self.EditMoneyOut)

        label = QtWidgets.QLabel(self)
        label.setObjectName("label")
        label.setText(_translate("Form", "今日钱箱现金放入"))
        self.EditMoneyIn = EditBox(self, eValueType.Float)
        self.EditMoneyIn.setObjectName("EditMoneyIn")
        self.EditMoneyIn.setText('0')
        self.formLayout_3.setWidget(Row, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
        self.formLayout_3.setWidget(Row, QtWidgets.QFormLayout.ItemRole.FieldRole, self.EditMoneyIn)


        Row += 1
        label = QtWidgets.QLabel(self)
        label.setObjectName("label")
        label.setText(_translate("Form", "理论钱箱总额"))
        self.LBTotalCash = QtWidgets.QLabel(self)
        self.LBTotalCash.setObjectName("LBTotalCash")
        self.LBTotalCash.setText(_translate("Form", "0"))
        self.formLayout.setWidget(Row, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
        self.formLayout.setWidget(Row, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LBTotalCash)

        label = QtWidgets.QLabel(self)
        label.setObjectName("label")
        label.setText(_translate("Form", "实际钱箱总额"))
        self.LBRealTotalCash = QtWidgets.QLabel(self)
        self.LBRealTotalCash.setObjectName("LBRealTotalCash")
        self.LBRealTotalCash.setText(_translate("Form", "0"))
        self.formLayout_2.setWidget(Row, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
        self.formLayout_2.setWidget(Row, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LBRealTotalCash)

        label = QtWidgets.QLabel(self)
        label.setObjectName("label")
        label.setText(_translate("Form", "钱箱差额"))
        self.LBCashMismatch = QtWidgets.QLabel(self)
        self.LBCashMismatch.setObjectName("LBCashMismatch")
        self.LBCashMismatch.setText(_translate("Form", "0"))
        self.formLayout_3.setWidget(Row, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
        self.formLayout_3.setWidget(Row, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LBCashMismatch)

        Row += 1
        label = QtWidgets.QLabel(self)
        label.setObjectName("label")
        label.setText(_translate("Form", "今日卡机应收"))
        self.LBTotalCard = QtWidgets.QLabel(self)
        self.LBTotalCard.setObjectName("LBTotalCard")
        self.LBTotalCard.setText(_translate("Form", "0"))
        self.formLayout.setWidget(Row, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
        self.formLayout.setWidget(Row, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LBTotalCard)

        label = QtWidgets.QLabel(self)
        label.setObjectName("label")
        label.setText(_translate("Form", "今日卡机实收"))
        self.LBRealTotalCard = EditBox(self, eValueType.Float)
        self.LBRealTotalCard.setObjectName("LBRealTotalCard")
        self.LBRealTotalCard.setText("0")
        self.formLayout_2.setWidget(Row, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
        self.formLayout_2.setWidget(Row, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LBRealTotalCard)

        label = QtWidgets.QLabel(self)
        label.setObjectName("label")
        label.setText(_translate("Form", "卡机差额"))
        self.LBCardMismatch = QtWidgets.QLabel(self)
        self.LBCardMismatch.setObjectName("LBCardMismatch")
        self.LBCardMismatch.setText(_translate("Form", "0"))
        self.formLayout_3.setWidget(Row, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
        self.formLayout_3.setWidget(Row, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LBCardMismatch)

        Row += 1
        label = QtWidgets.QLabel(self)
        label.setObjectName("label")
        label.setText(_translate("Form", "今日总收入"))
        self.LBTotalIncome = QtWidgets.QLabel(self)
        self.LBTotalIncome.setObjectName("LBTotalIncome")
        self.LBTotalIncome.setText(_translate("Form", "0"))
        self.formLayout.setWidget(Row, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
        self.formLayout.setWidget(Row, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LBTotalIncome)

        # label = QtWidgets.QLabel(self)
        # label.setObjectName("label")
        # label.setText(_translate("Form", "今日总实际收入"))
        # self.LBRealTotalIncome = QtWidgets.QLabel(self)
        # self.LBRealTotalIncome.setObjectName("LBRealTotalIncome")
        # self.LBRealTotalIncome.setText(_translate("Form", "0"))
        # self.formLayout_2.setWidget(Row, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
        # self.formLayout_2.setWidget(Row, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LBRealTotalIncome)
        #
        # label = QtWidgets.QLabel(self)
        # label.setObjectName("label")
        # label.setText(_translate("Form", "今日总收入差"))
        # self.LBIncomeMismatch = QtWidgets.QLabel(self)
        # self.LBIncomeMismatch.setObjectName("LBIncomeMismatch")
        # self.LBIncomeMismatch.setText(_translate("Form", "0"))
        # self.formLayout_3.setWidget(Row, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
        # self.formLayout_3.setWidget(Row, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LBIncomeMismatch)

        self.horizontalLayout.addLayout(self.formLayout)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.horizontalLayout.addLayout(self.formLayout_3)
        self.MainLayout.addLayout(self.horizontalLayout)

        self.BtnLayout = QtWidgets.QHBoxLayout(self)
        self.BtnLayout.addWidget(self.BtnConfirm)
        self.BtnLayout.addWidget(self.BtnReset)
        self.MainLayout.addLayout(self.BtnLayout)
        self.setLayout(self.MainLayout)
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.BtnConfirm.setText(_translate("Form", "确认"))
        self.BtnReset.setText(_translate("Form", "重置"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ui = CEODPanelBase()
    ui.show()
    sys.exit(app.exec())
