# Form implementation generated from reading ui file 'Ui/EODPanel.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from QtApp.Base import CFrame, CWidget, CPushButton
from QtApp.Base.EditBox import eValueType, EditBox


class CEODPanelBase(CFrame):
    def __init__(self, aParent=None):
        CFrame.__init__(self, aParent)
        self.setupUi()

    def setupUi(self):
        self.setObjectName("EODPanel")
        self.MainLayout = QtWidgets.QVBoxLayout(self)
        self.BtnConfirm = CPushButton(self)
        self.BtnConfirm.setObjectName("BtnConfirm")
        self.BtnReset = CPushButton(self)
        self.BtnReset.setObjectName("BtnReset")

        self.gridLayout = QtWidgets.QGridLayout(self)

        _translate = QtCore.QCoreApplication.translate

        self.Values = {}
        for i in [50, 20, 10, 5, 2, 1, 0.5, 0.1, 0.05, 0.02, 0.01]:
            formLayout = QtWidgets.QFormLayout(self)
            label = QtWidgets.QLabel(self)
            label.setObjectName(f"label{i}")
            if i >= 1:
                label.setText(_translate("Form", f"£{i} 数量"))
            else:
                label.setText(_translate("Form", f"{round(i * 100)}p 数量"))
            ValueBox = EditBox(self, eValueType.Int)
            ValueBox.setText('0')
            ValueBox.setMinimum(0)
            formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
            formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, ValueBox)
            Row = len(self.Values) // 3
            self.gridLayout.addLayout(formLayout,Row,len(self.Values) % 3)
            self.Values[i] = ValueBox

        Row = len(self.Values) // 3 + 1
        label = QtWidgets.QLabel(self)
        label.setObjectName("label")
        label.setText(_translate("Form", "今日总现金收入"))
        self.LBTodayTotalCash = QtWidgets.QLabel(self)
        self.LBTodayTotalCash.setObjectName("label")
        self.LBTodayTotalCash.setText(_translate("Form", "0"))
        formLayout = QtWidgets.QFormLayout(self)
        formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
        formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LBTodayTotalCash)
        self.gridLayout.addLayout(formLayout, Row, 0)

        label = QtWidgets.QLabel(self)
        label.setObjectName("label")
        label.setText(_translate("Form", "今日钱箱现金取出"))
        self.EditMoneyOut = EditBox(self, eValueType.Float)
        self.EditMoneyOut.setObjectName("EditMoneyOut")
        self.EditMoneyOut.setText('0')
        formLayout = QtWidgets.QFormLayout(self)
        formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
        formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.EditMoneyOut)
        self.gridLayout.addLayout(formLayout, Row, 1)

        label = QtWidgets.QLabel(self)
        label.setObjectName("label")
        label.setText(_translate("Form", "今日钱箱现金放入"))
        self.EditMoneyIn = EditBox(self, eValueType.Float)
        self.EditMoneyIn.setObjectName("EditMoneyIn")
        self.EditMoneyIn.setText('0')
        formLayout = QtWidgets.QFormLayout(self)
        formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
        formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.EditMoneyIn)
        self.gridLayout.addLayout(formLayout, Row, 2)

        Row += 1
        label = QtWidgets.QLabel(self)
        label.setObjectName("label")
        label.setText(_translate("Form", "理论钱箱总额"))
        self.LBTotalCash = QtWidgets.QLabel(self)
        self.LBTotalCash.setObjectName("LBTotalCash")
        self.LBTotalCash.setText(_translate("Form", "0"))
        formLayout = QtWidgets.QFormLayout(self)
        formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
        formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LBTotalCash)
        self.gridLayout.addLayout(formLayout, Row, 0)

        label = QtWidgets.QLabel(self)
        label.setObjectName("label")
        label.setText(_translate("Form", "实际钱箱总额"))
        self.LBRealTotalCash = QtWidgets.QLabel(self)
        self.LBRealTotalCash.setObjectName("LBRealTotalCash")
        self.LBRealTotalCash.setText(_translate("Form", "0"))
        formLayout = QtWidgets.QFormLayout(self)
        formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
        formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LBRealTotalCash)
        self.gridLayout.addLayout(formLayout, Row, 1)

        label = QtWidgets.QLabel(self)
        label.setObjectName("label")
        label.setText(_translate("Form", "钱箱差额"))
        self.LBCashMismatch = QtWidgets.QLabel(self)
        self.LBCashMismatch.setObjectName("LBCashMismatch")
        self.LBCashMismatch.setText(_translate("Form", "0"))
        formLayout = QtWidgets.QFormLayout(self)
        formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
        formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LBCashMismatch)
        self.gridLayout.addLayout(formLayout, Row, 2)

        Row += 1
        label = QtWidgets.QLabel(self)
        label.setObjectName("label")
        label.setText(_translate("Form", "今日卡机应收"))
        self.LBTotalCard = QtWidgets.QLabel(self)
        self.LBTotalCard.setObjectName("LBTotalCard")
        self.LBTotalCard.setText(_translate("Form", "0"))
        formLayout = QtWidgets.QFormLayout(self)
        formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
        formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LBTotalCard)
        self.gridLayout.addLayout(formLayout, Row, 0)

        label = QtWidgets.QLabel(self)
        label.setObjectName("label")
        label.setText(_translate("Form", "今日卡机实收"))
        self.EditRealTotalCard = EditBox(self, eValueType.Float)
        self.EditRealTotalCard.setObjectName("LBRealTotalCard")
        self.EditRealTotalCard.setText("0")
        formLayout = QtWidgets.QFormLayout(self)
        formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
        formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.EditRealTotalCard)
        self.gridLayout.addLayout(formLayout, Row, 1)

        label = QtWidgets.QLabel(self)
        label.setObjectName("label")
        label.setText(_translate("Form", "卡机差额"))
        self.LBCardMismatch = QtWidgets.QLabel(self)
        self.LBCardMismatch.setObjectName("LBCardMismatch")
        self.LBCardMismatch.setText(_translate("Form", "0"))
        formLayout = QtWidgets.QFormLayout(self)
        formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
        formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LBCardMismatch)
        self.gridLayout.addLayout(formLayout, Row, 2)

        Row += 1
        label = QtWidgets.QLabel(self)
        label.setObjectName("label")
        label.setText(_translate("Form", "今日总收入"))
        self.LBTotalIncome = QtWidgets.QLabel(self)
        self.LBTotalIncome.setObjectName("LBTotalIncome")
        self.LBTotalIncome.setText(_translate("Form", "0"))
        formLayout = QtWidgets.QFormLayout(self)
        formLayout.setWidget(Row, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
        formLayout.setWidget(Row, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LBTotalIncome)
        self.gridLayout.addLayout(formLayout, Row, 0)

        label = QtWidgets.QLabel(self)
        label.setObjectName("label")
        label.setText(_translate("Form", "今日总实际收入"))
        self.LBRealTotalIncome = QtWidgets.QLabel(self)
        self.LBRealTotalIncome.setObjectName("LBRealTotalIncome")
        self.LBRealTotalIncome.setText(_translate("Form", "0"))
        formLayout = QtWidgets.QFormLayout(self)
        formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
        formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LBRealTotalIncome)
        self.gridLayout.addLayout(formLayout, Row, 1)

        label = QtWidgets.QLabel(self)
        label.setObjectName("label")
        label.setText(_translate("Form", "今日总收入差"))
        self.LBIncomeMismatch = QtWidgets.QLabel(self)
        self.LBIncomeMismatch.setObjectName("LBIncomeMismatch")
        self.LBIncomeMismatch.setText(_translate("Form", "0"))
        formLayout = QtWidgets.QFormLayout(self)
        formLayout.setWidget(Row, QtWidgets.QFormLayout.ItemRole.LabelRole, label)
        formLayout.setWidget(Row, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LBIncomeMismatch)
        self.gridLayout.addLayout(formLayout, Row, 2)

        self.MainLayout.addLayout(self.gridLayout)

        self.BtnLayout = QtWidgets.QHBoxLayout(self)
        self.BtnLayout.addWidget(self.BtnConfirm)
        self.BtnLayout.addWidget(self.BtnReset)
        self.MainLayout.addLayout(self.BtnLayout)
        self.setLayout(self.MainLayout)
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.BtnConfirm.setText(_translate("Form", "确认"))
        self.BtnReset.setText(_translate("Form", "重置"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ui = CEODPanelBase()
    ui.show()
    sys.exit(app.exec())
