# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui/FinalStatus.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from TableInfoStore import TableInfoStore
from QtApp.FinalStatusBase import FinalStatusBase
from functools import partial


class FinalStatusPanel(FinalStatusBase):
    def __init__(self, parant):
        FinalStatusBase.__init__(self, parant)
        self.total = 0
        self.cash = 0
        self.card = 0
        self.ServiceChargePercent = 0.1
        self.DiscountPercent = 0
        self.AddCashEvent = None
        self.AddCardEvent = None
        self.AddDiscountEvent = None
        self.AddServiceChargeEvent = None
        self.BtnCashRemove_2.pressed.connect(self.RemoveCash)
        self.BtnCardRemove.pressed.connect(self.RemoveCard)
        self.BtnPay5Cash.pressed.connect(partial(self.AddCash, 5))
        self.BtnPay10Cash.pressed.connect(partial(self.AddCash, 10))
        self.BtnPay20Cash.pressed.connect(partial(self.AddCash, 20))
        self.BtnPayByCard.pressed.connect(self.AddRestCard)
        self.BtnPayByCash.pressed.connect(self.AddRestCash)

    def DisplayTable(self, TableInfo: TableInfoStore):
        self.Clear()
        self.LBTableNumber.setText(TableInfo.TableID)
        self.LBStartTime.setText(TableInfo.StartTime)
        self.LBEndTime.setText(TableInfo.EndTime)
        self.LBNumOfPeople.setText(TableInfo.NumOfPeople)
        self.total = TableInfo.GetTotalAmount()
        if TableInfo.Cash is None:
            self.cash = 0
        else:
            self.cash = float(TableInfo.Cash)
        if TableInfo.Card is None:
            self.card = 0
        else:
            self.card = float(TableInfo.Card)

        self.LBTotalAmount.setText(str(self.total))
        self.EditBoxToPayAmount.setValue(self.total)
        self.LBPaidCard.setText('0.00')
        self.LBPaiedCash.setText('0.00')

    def Clear(self):
        self.card = 0
        self.cash = 0
        self.total = 0

    def DisplayAllInfo(self):
        self.LBPaiedCash_2.setText(str(round(self.cash, 2)))
        self.LBPaidCard.setText(str(round(self.card, 2)))
        self.LBTotalAmount.setText(str(round(self.total)))
        ServiceCharge = round(self.total * self.ServiceChargePercent)
        self.LBServiceCharge.setText(str(ServiceCharge))
        DiscountAmount = round(self.total * self.DiscountPercent)
        self.LBDiscountAmount.setText((str(DiscountAmount)))
        LeftToPay = self.total + ServiceCharge - DiscountAmount - self.card - self.cash
        if LeftToPay >= 0:
            self.EditBoxToPayAmount.setValue(str(LeftToPay))
            self.LBLablePayment.setText('未付')
        else:
            self.EditBoxToPayAmount.setValue(str(-LeftToPay))
            self.LBLablePayment.setText('找零')

    def ReopenConnect(self, Event):
        self.BtnReOpen.pressed.connect(Event)

    def CleanTableConnect(self, Event):
        self.BtnCleanTable.pressed.connect(Event)

    def PrintReceiptConnect(self, Event):
        self.BtnPrintReceipt.pressed.connect(Event)

    def RemoveCash(self):
        self.cash = 0
        self.AddCashEvent(0)
        self.DisplayAllInfo()

    def RemoveCard(self):
        self.card = 0
        self.AddCardEvent(0)
        self.DisplayAllInfo()

    def AddCash(self, Amount):
        self.cash += Amount
        self.AddCashEvent(self.cash)
        self.DisplayAllInfo()

    def AddCard(self, Amount):
        self.card += Amount
        self.AddCardEvent(self.cash)
        self.DisplayAllInfo()

    def AddRestCash(self):
        self.cash += self.EditBoxToPayAmount.value()
        self.AddCashEvent(self.cash)
        self.DisplayAllInfo()

    def AddRestCard(self):
        self.card += self.EditBoxToPayAmount.value()
        self.AddCardEvent(self.card)
        self.DisplayAllInfo()

    def AddCashConnect(self, Event):
        self.AddCashEvent = Event

    def AddCardConnect(self, Event):
        self.AddCardEvent = Event

    def AddDiscountConnect(self, Event):
        self.AddDiscountEvent = Event

    def AddServiceChargeConnect(self, Event):
        self.AddServiceChargeEvent = Event


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ui = FinalStatusPanel(None)
    ui.show()
    sys.exit(app.exec_())
