# Form implementation generated from reading ui file 'Ui/AccountDetail.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from QtApp.Base import CFrame, CWidget, CPushButton
from QtApp.Base.EditBox import eValueType, EditBox
from QtApp.Base.CAccountCombo import AccountCombo


class InitialTakeAwayPanel(CFrame):
    def __init__(self, aParent=None):
        CFrame.__init__(self, aParent)
        # if aParent is not None:
        #     self.BlockPanel = aParent.BlockPanel
        # else:
        #     self.BlockPanel = None
        self.setupUi()
        self.AccountID = None
        self.RefreshEvent = None
        # self.ButtonConfirm.pressed.connect(self.SaveAndClose)
        # if self.BlockPanel is not None:
        #     self.pushButtonReturn.pressed.connect(self.BlockPanel.Close)
        # self.SetBackgoundColor('Yellow')

    def setupUi(self):
        self.setObjectName("Form")
        self.resize(400, 300)
        self.formLayoutWidget = CWidget(aParent=self)
        self.formLayoutWidget.setGeometry(QtCore.QRect(19, 19, 371, 121))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.EditBoxName = EditBox(self.formLayoutWidget, eValueType.String)
        self.EditBoxName.setObjectName("EditBoxName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.EditBoxName)

        self.label_4 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.EditNumber = EditBox(self.formLayoutWidget, eValueType.String)
        self.EditBoxName.setObjectName("EditNumber")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.EditNumber)

        self.label_5 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.EditNote = EditBox(self.formLayoutWidget, eValueType.String)
        self.EditNote.setObjectName("EditBoxName")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.EditNote)

        self.label_6 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.ComboAccount = AccountCombo(self.formLayoutWidget)
        self.ComboAccount.setObjectName("ComboAccount")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.ComboAccount)

        self.ButtonConfirm = CPushButton(self)
        self.ButtonConfirm.setGeometry(QtCore.QRect(30, 220, 75, 24))
        self.ButtonConfirm.setObjectName("ButtonConfirm")
        self.ButtonConfirm.pressed.connect(self.NewTakeAway)
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)
        self.OpenOrderEvent = None

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", ""))
        self.label_2.setText(_translate("Form", "外卖"))
        self.label_3.setText(_translate("Form", "名字"))
        self.label_4.setText(_translate("Form", "电话号码"))
        self.label_5.setText(_translate("Form", "备注"))
        self.label_6.setText(_translate("Form", "账户"))
        self.ButtonConfirm.setText(_translate("Form", "确认"))

    def NewTakeAway(self):
        OrderId = self.DataBase.InitialOrder(0, None, self.EditBoxName.value(), self.EditNumber.text(),
                                             self.EditNote.value(), self.ComboAccount.CurrentAccountID())
        if self.OpenOrderEvent is not None:
            self.OpenOrderEvent(OrderId)

    def Clear(self):
        self.EditNumber.setText('')
        self.EditNote.setText('')
        self.EditBoxName.setText('')
        self.ComboAccount.DisplayAccount()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ui = InitialTakeAwayPanel()
    ui.setupUi()
    ui.show()
    sys.exit(app.exec())
