# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui/InitialTable.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from QtApp.Base.EditBox import EditBox, eValueType
from QtApp.Base import CFrame, CWidget, CPushButton
from QtApp.Base.FlowLayout import FlowLayout
from functools import partial

class InitialTable(CFrame):
    def __init__(self, aParant):
        CFrame.__init__(self, aParant)
        self.TableButClickEvent = None
        self.setupUi()

    def setupUi(self):
        self.setObjectName("InitialTable")
        self.resize(469, 361)
        self.vbox = QtWidgets.QVBoxLayout(self)

        self.formLayout = QtWidgets.QFormLayout(self)
        self.vbox.addLayout(self.formLayout)
        # self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")

        self.label = QtWidgets.QLabel(self)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.LBTableNumber = QtWidgets.QLabel(self)
        self.LBTableNumber.setObjectName("LBTableNumber")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LBTableNumber)
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.EditBoxNumOfPeople = EditBox(self, eValueType.Int)
        self.EditBoxNumOfPeople.setMinimum(1)
        self.EditBoxNumOfPeople.setMaximum(30)
        self.EditBoxNumOfPeople.setObjectName("EditBoxNumOfPeople")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.EditBoxNumOfPeople)
        self.weget = CWidget(self)
        self.vbox.addWidget(self.weget)

        self.flowLayout = FlowLayout(self.weget)
        self.weget.setLayout(self.flowLayout)
        for i in range(1, 9):
            Btn = CPushButton(self)
            Btn.setText(f"{i}人")
            Btn.pressed.connect(partial(self.OpenTableEvent, i))
            self.flowLayout.addWidget(Btn)
        self.gridLayout = QtWidgets.QGridLayout(self)

        self.vbox.addLayout(self.gridLayout)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.BtnOpenTable = CPushButton(self)
        self.BtnOpenTable.setObjectName("OpenTable")
        self.gridLayout.addWidget(self.BtnOpenTable, 0, 0, 1, 1)

        self.BtnOpenTable.pressed.connect(self.OpenTableEvent)

        self.setLayout(self.vbox)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def setKeyBoardEvent(self, Event):
        self.EditBoxNumOfPeople.OpenKeyboardEvent = Event

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "桌号"))
        self.LBTableNumber.setText(_translate("Form", "None"))
        self.label_2.setText(_translate("Form", "人数"))
        self.BtnOpenTable.setText(_translate("Form", "开台"))

    def DisplayTable(self, TableNumber):
        self.TableNumber = TableNumber
        self.LBTableNumber.setText(str(TableNumber))
        self.EditBoxNumOfPeople.setText('2')

    def OpenTableEvent(self, NumberOfPeople=None):
        try:
            TableNumber = self.TableNumber
            if NumberOfPeople is None:
                NumberOfPeople = self.EditBoxNumOfPeople.value()
            self.Logger.info(f'Table {TableNumber} open, Number Of People {NumberOfPeople}.')
            if TableNumber is not None:
                self.DataBase.InitialOrder(TableNumber, NumberOfPeople)
                self.TableButClickEvent(TableNumber)
        except Exception as e:
            self.Logger.error(f'Error during Table {self.TableNumber} open', exc_info=e)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ui = InitialTable(None)
    ui.show()
    sys.exit(app.exec_())
