# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui/JumpWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from QtApp.Base import CFrame, CPushButton


class JumpWindow(CFrame):
    def __init__(self, aParant):
        CFrame.__init__(self, aParant)
        self.setupUi()
        self.BlockPanel = None
        self.BtnNo.pressed.connect(self.CloseWindow)
        self.BtnYes.pressed.connect(self.YesEvent)
        self.ToDOEvent = None

    def setupUi(self):
        self.setObjectName("Form")
        self.setAutoFillBackground(True)
        # self.widget = QtWidgets.QWidget(self)
        # self.widget.setGeometry(QtCore.QRect(0, 0, 391, 291))
        # self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LBQuestion = QtWidgets.QLabel(self)
        self.LBQuestion.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.LBQuestion.setAlignment(QtCore.Qt.AlignCenter)
        self.LBQuestion.setObjectName("LBQuestion")
        self.LBQuestion.setMaximumSize(QtCore.QSize(16777215, 300))
        self.horizontalLayout.addWidget(self.LBQuestion)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BtnYes = CPushButton(self)
        self.BtnYes.setMaximumSize(QtCore.QSize(150, 16777215))
        self.BtnYes.setMinimumSize(QtCore.QSize(100, 50))
        self.BtnYes.setObjectName("BtnYes")
        self.horizontalLayout_2.addWidget(self.BtnYes)
        self.BtnNo = CPushButton(self)
        self.BtnNo.setMaximumSize(QtCore.QSize(150, 16777215))
        self.BtnNo.setMinimumSize(QtCore.QSize(100, 50))
        self.BtnNo.setObjectName("BtnNo")
        self.horizontalLayout_2.addWidget(self.BtnNo)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Confirm Window"))
        self.LBQuestion.setText(_translate("Form", "Title"))
        self.BtnYes.setText(_translate("Form", "是"))
        self.BtnNo.setText(_translate("Form", "不是"))

    def SetQuestion(self, text):
        self.LBQuestion.setText(text)

    def Yesconnect(self, event):
        self.ToDOEvent = event

    def YesEvent(self):
        if self.ToDOEvent is not None:
            self.ToDOEvent()
        self.CloseWindow()

    def OpenWindow(self):
        try:
            self.BlockPanel.setVisible(True)
            self.setVisible(True)
            self.BlockPanel.resize(self.parent().width(), self.parent().height())
            self.resize(600, 300)
            self.move(self.parent().width() // 2 - 300, self.parent().height() // 2 - 150)

            self.raise_()
            self.BlockPanel.lower()
            self.BlockPanel.stackUnder(self)
            self.BlockPanel.mousePressEvent = lambda x: self.CloseWindow()
        except Exception as e:
            self.Logger.error(f'Error during show jump window', exc_info=e)

    def CloseWindow(self):
        self.setVisible(False)
        self.BlockPanel.setVisible(False)
        self.ToDOEvent = None


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ui = JumpWindow()
    ui.show()
    sys.exit(app.exec_())
