# Form implementation generated from reading ui file 'Ui/keyboard.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from QtApp.Base.KeyBoardBut import KeyBoardBtn
from QtApp.Base import CFrame, CWidget


class KeyBoardPanel(CFrame):
    def __init__(self, aParant):
        CFrame.__init__(self, aParant)
        self.Btns = {}
        self.target = None
        self.setupUi()
        self.OriValue = None

    def setupUi(self):
        self.setObjectName("Form")
        self.resize(400, 300)
        self.gridLayoutWidget = CWidget(aParent=self)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.SetBackgoundColor('Yellow')
        k = 0
        for i in [7, 8, 9, 4, 5, 6, 1, 2, 3, 0, 'Dot', 'Delete']:
            # 'Enter': No need Enter. As user can click other place to quit.
            Btn = KeyBoardBtn(aParent=self.gridLayoutWidget)
            Btn.setObjectName(f"Btn{i}")
            Btn.setupUi(i)
            self.gridLayout.addWidget(Btn, k // 3, k % 3, 1, 1)
            k += 1
            self.Btns[i] = Btn

        self.setLayout(self.gridLayout)
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))

    def ConnectWidgets(self, Widgets):
        pass

    def setTarget(self, target):
        self.target = target
        for i in self.Btns:
            self.Btns[i].setTarget(target)
        self.MoveToTarget(target)

    def removeTarget(self):
        self.target = None
        for i in self.Btns:
            self.Btns[i].removeTarget()

    def MoveToTarget(self, target):
        width = 300
        height = 300
        x1 = target.AbsX()
        x2 = x1 + target.width()
        y1 = target.AbsY()
        y2 = y1 + target.height()
        x = x1
        y = y2
        if self.parent().width() - x1 < width:
            x = self.parent().width() - width
        if self.parent().height() - y2 < height:
            y = y1 - height
        self.move(x, y)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ui = KeyBoardPanel(None)
    ui.show()
    sys.exit(app.exec())
