# -*- coding: utf-8 -*-
import pandas as pd
from functools import partial
# Form implementation generated from reading ui file 'Ui/Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from QtApp.MenuPage import MenuPage


class Menu(QtWidgets.QFrame):
    def __init__(self, parant):
        QtWidgets.QFrame.__init__(self, parant)
        self.MenuENName = {1: "ColdFood", 2: "HotFood", 3: "MainFood", 4: "Desert", 5: "Drink"}
        self.MenuCNName = {1: "冷菜", 2: "热菜", 3: "主食", 4: "甜品", 5: "饮品"}

    def setupUi(self):
        self.setObjectName("Menu")
        self.resize(546, 338)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 495, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ButList = {}
        for i in self.MenuCNName:
            But = QtWidgets.QPushButton(self.horizontalLayoutWidget)
            But.setObjectName("Btn" + self.MenuENName[i])
            self.horizontalLayout.addWidget(But)
            self.ButList[i] = But
            But.pressed.connect(partial(self.ActivePage, i))
        self.MenuPageList = {}
        for type in self.MenuENName:
            Page = MenuPage(self, self.MenuENName[type])
            self.MenuPageList[type] = Page
            Page.setGeometry(QtCore.QRect(19, 69, 481, 241))
            Page.setFrameShape(QtWidgets.QFrame.StyledPanel)
            Page.setFrameShadow(QtWidgets.QFrame.Raised)

        self.ActivePage(1)
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def AddItems(self, data: pd.DataFrame):
        data.apply(self.AddItem, axis=1)

    def AddItem(self, data: pd.Series):
        self.MenuPageList[data['FoodType']].AddItem(data)

    def ActivePage(self, type):
        print(type)
        for i in self.MenuPageList:
            if i == type:
                print(i)
                self.MenuPageList[i].setVisible(True)
            else:
                self.MenuPageList[i].setVisible(False)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Menu"))
        for i in self.MenuCNName:
            self.ButList[i].setText(_translate("Form", self.MenuCNName[i]))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ui = Menu(None)
    ui.setupUi()
    MenuItemList = pd.DataFrame([[0, 'Test1', '测试1', 1], [1, 'Test2', '测试2', 2]],
                                columns=['ID', 'FoodENName', 'FoodCNName', 'FoodType'])
    ui.AddItems(MenuItemList)
    ui.show()
    sys.exit(app.exec_())
