# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui/OrderList.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from QtApp.Base.OrderTableWdiget import TableWdiget
from collections import defaultdict
from TableInfoStore import OrderInfo


class OrderListPanel(QtWidgets.QFrame):
    def __init__(self, parant):
        QtWidgets.QFrame.__init__(self, parant)
        self.setupUi()
        self.Orders = []

    def setupUi(self):
        self.setObjectName("orderList")
        self.tableView = TableWdiget(self)
        self.tableView.setObjectName("tableView")
        mainLayout = QtWidgets.QHBoxLayout()
        mainLayout.addWidget(self.tableView)
        self.setLayout(mainLayout)
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "OrderList"))

    def selectedRow(self):
        return self.tableView.selectedRow

    def DisplayTable(self, TableInfo):
        self.tableView.Clear()
        for order in TableInfo.Orders.values():
            self.Orders.append(order)
            self.tableView.addRow(order)

    def Clear(self):
        self.tableView.Clear()

    def AddOrder(self, Order):
        self.Orders.append(Order)
        self.tableView.addRow(Order)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ui = OrderListPanel(None)
    ui.show()
    ui.tableView.test()
    sys.exit(app.exec_())
