# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui/Status.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets, QtWebEngineWidgets, QtPrintSupport
from TableInfoStore import TableInfoStore
from functools import partial


class Receipt(QtWidgets.QFrame):
    def __init__(self, parant):
        QtWidgets.QFrame.__init__(self, parant)
        self.TableNumber = None

    def setupUi(self, TableInfo: TableInfoStore):
        self.setObjectName("Form")
        self.resize(468, 1000)
        self.setObjectName("Form")
        self.web_view = QtWebEngineWidgets.QWebEngineView(self)
        # load HTML content
        receiptform = ('''<html><body><style type="text/css">.receipt_main {display: grid;width = 100%;
                grid-template-columns: 1fr 1fr;align-items: center;}.itemname{flex-wrap: wrap;}
                .itemprice{margin-right:0;margin-left: auto;}</style>
                <div id="receipt">
                <div id="receipt_head" style="text-align: center;">
                <div id="icon"><img src="file://{Path_To_LOGO}" style="width:50px;height:50px;"></div>
                <div id="address">{ADDRESS}</div>
                </div><hr>
                <div id="receipt_info">VAT No: {VATNO}<br>Date: {TIME}<br> ORDERID: {ORDERID}<br>Table Number: {TABLE_NUMBER}
                </div></div><hr>'''.replace('{Path_To_LOGO}', 'D:/Code/web_python/App/img/Login.png')
                       .replace('{ADDRESS}', 'Address')
                       .replace('{VATNO}', '')
                       .replace('{TIME}', TableInfo.EndTime)
                       .replace('{ORDERID}', TableInfo.OrderID)
                       .replace('{TABLE_NUMBER}', TableInfo.TableID))
        Total = TableInfo.GetTotalAmount()
        for OrderID in TableInfo.Orders:
            Order = TableInfo.Orders[OrderID]

            receiptform += ('''<div id="item" class="receipt_main">
                    <div class="itemname">{QTY} x {NAME} {NOTE}</div>
                    <div class="itemprice">£{PRICE}</div>
                    </div>'''.replace('{QTY}', str(int(Order.Qty))).replace('{NAME}', Order.NameEN)
                            .replace('{NOTE}', Order.Note).replace('{PRICE}', str(round(Order.UnitPrice, 2))))
        receiptform += '''<hr><div id='Total' class='receipt_main'>
                    <div class="itemname">SUBTOTAL</div>
                    <div class="itemprice">£{TOTAL}</div></div>'''.replace('{TOTAL}', str(round(Total, 2)))
        if TableInfo.ServiceCharge != 0:
            receiptform += ('''<div id="Total" class="receipt_main">
                    <div class="itemname">{SERVICE_CHARGE_PERCENT}% Service Charge</div>
                    <div class="itemprice">£{SERVICE_CHARGE_AMOUNT}</div></div>'''
                            .replace('SERVICE_CHARGE_PERCENT}', str(round(TableInfo.ServiceCharge, 1)))
                            .replace('{SERVICE_CHARGE_AMOUNT}', str(round(Total * TableInfo.ServiceCharge, 2))))
            Total = Total * (1 + TableInfo.ServiceCharge)
        DiscountPercent = round(TableInfo.Discount)
        if DiscountPercent > 0:
            receiptform += ('''<div id='discount' class='receipt_main'>
                    <div class="itemname">{DISCOUNT_PERCENT}%DISCOUNT</div>
                    <div class="itemprice">£{DISCOUNT_AMOUNT}}</div></div><br>'''
                            .replace('DISCOUNT_PERCENT}', str(round(TableInfo.Discount)))
                            .replace('{DISCOUNT_AMOUNT}', str(round(Total * TableInfo.Discount, 2))))
            Total = Total * (1 - DiscountPercent)

        receiptform += '''<hr><div id="Total" class="receipt_main"><div class="itemname">12.5% VAT included</div></div>
                <div id="Total" class="receipt_main"><div class="itemname">TOTAL</div>
                <div class="itemprice">£{TOTAL}</div></div><hr>
                <div id="receipt_foot" style="text-align: center;">
                Thanks for visiting!<br>You can find us on instagram<br> @usagi_animemaid_cafe</div></div></body></html>
                '''.replace('{TOTAL}', str(round(Total, 2)))
        self.web_view.setHtml(receiptform)
        # set the widget as the main window's central widget
        vview = QtWidgets.QVBoxLayout(self)
        vview.addWidget(self.web_view)

        # self.label_3 = QtWidgets.QPushButton(self)
        # vview.addWidget(self.label_3)
        # self.label_3.pressed.connect(self.print_me2)
        #
        # _translate = QtCore.QCoreApplication.translate
        # self.label_3.setText(_translate("Form", "开始时间"))
        self.setLayout(vview)

        QtCore.QMetaObject.connectSlotsByName(self)

    def print_me2(self):
        printer = QtPrintSupport.QPrinter()
        printer.setOutputFormat(QtPrintSupport.QPrinter.NativeFormat)
        printer.setPrinterName('ET-2850 Series(Network)')
        painter = QtGui.QPainter(printer)
        xscale = printer.pageRect(QtPrintSupport.QPrinter.Unit.DevicePixel).width() / self.width()
        yscale = printer.pageRect(QtPrintSupport.QPrinter.Unit.DevicePixel).height() / self.height()
        scale = min(xscale, yscale)
        painter.translate(printer.paperRect(QtPrintSupport.QPrinter.Unit.DevicePixel).center())
        painter.scale(scale, scale)
        painter.translate((self.width() / 2) * -1, (self.height() / 2) * -1)

        self.web_view.render(painter, QtCore.QPoint())
        painter.end()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ui = Receipt(None)
    ui.show()
    sys.exit(app.exec_())
