# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui/SettingPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from Config import Config


class SettingPanelBase(QtWidgets.QFrame):
    def __init__(self, parant, Setting):
        QtWidgets.QFrame.__init__(self, parant)
        self.Setting = Setting
        self.MenuENName = self.Setting.GetValue(Config.ValueSetting.Manu.EN_NAME)
        self.MenuCNName = self.Setting.GetValue(Config.ValueSetting.Manu.CN_NAME)
        self.setupUi()

    def setupUi(self):
        self.setObjectName("Form")
        self.resize(396, 291)
        self.formLayoutWidget = QtWidgets.QWidget(self)
        self.formLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 301, 281))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")

        row = 0

        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(row, QtWidgets.QFormLayout.LabelRole, self.label)

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CBCashierPrinter = QtWidgets.QComboBox(self.formLayoutWidget)
        self.CBCashierPrinter.setObjectName("CBCashierPrinter")
        self.horizontalLayout_2.addWidget(self.CBCashierPrinter)
        self.BtnCashierTestPrint = QtWidgets.QPushButton(self.formLayoutWidget)
        self.BtnCashierTestPrint.setObjectName("BtnCashierTestPrint")
        self.horizontalLayout_2.addWidget(self.BtnCashierTestPrint)
        self.formLayout.setLayout(row, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)

        self.LabelsPrinter = {}
        self.BtnsPrinterTest = {}
        self.CBsPrinter = {}
        for i in self.MenuENName:
            row += 1
            label = QtWidgets.QLabel(self.formLayoutWidget)
            label.setObjectName(f"label_{self.MenuENName[i]}")
            self.formLayout.setWidget(row, QtWidgets.QFormLayout.LabelRole, label)
            self.LabelsPrinter[i] = label

            horizontalLayout = QtWidgets.QHBoxLayout()
            horizontalLayout.setObjectName("horizontalLayout")
            CBPrinter = QtWidgets.QComboBox(self.formLayoutWidget)
            CBPrinter.setObjectName(f"CB{self.MenuENName}Printer")
            horizontalLayout.addWidget(CBPrinter)
            BtnTestPrinter = QtWidgets.QPushButton(self.formLayoutWidget)
            BtnTestPrinter.setObjectName(f"Btn{self.MenuENName}TestPrint")
            horizontalLayout.addWidget(BtnTestPrinter)
            self.formLayout.setLayout(row, QtWidgets.QFormLayout.FieldRole, horizontalLayout)
            self.CBsPrinter[i] = CBPrinter
            self.BtnsPrinterTest[i] = BtnTestPrinter

        row += 1
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(row, QtWidgets.QFormLayout.LabelRole, self.label_3)

        self.CBServiceChargePercent = QtWidgets.QComboBox(self.formLayoutWidget)
        self.CBServiceChargePercent.setObjectName("CBServiceChargePercent")
        self.formLayout.setWidget(row, QtWidgets.QFormLayout.FieldRole, self.CBServiceChargePercent)

        row += 1
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(row, QtWidgets.QFormLayout.LabelRole, self.label_4)

        self.CBDiscountPercentA = QtWidgets.QComboBox(self.formLayoutWidget)
        self.CBDiscountPercentA.setObjectName("CBDiscountPercentA")
        self.formLayout.setWidget(row, QtWidgets.QFormLayout.FieldRole, self.CBDiscountPercentA)

        row += 1
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(row, QtWidgets.QFormLayout.LabelRole, self.label_5)

        self.CBDiscountPercentB = QtWidgets.QComboBox(self.formLayoutWidget)
        self.CBDiscountPercentB.setObjectName("CBDiscountPercentB")
        self.formLayout.setWidget(row, QtWidgets.QFormLayout.FieldRole, self.CBDiscountPercentB)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "收银打印机"))
        for i in self.MenuCNName:
            self.LabelsPrinter[i].setText(_translate("Form", self.MenuCNName[i]))
            self.BtnsPrinterTest[i].setText(_translate("Form", "测试打印"))
        self.label_3.setText(_translate("Form", "服务费比例"))
        self.BtnCashierTestPrint.setText(_translate("Form", "测试打印"))
        self.label_4.setText(_translate("Form", "折扣A"))
        self.label_5.setText(_translate("Form", "折扣B"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ui = SettingPanelBase(None)
    ui.show()
    sys.exit(app.exec_())
