# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui/SettingPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PrinterControl import PrinterControl


class SettingPanel(QtWidgets.QFrame):
    def __init__(self, parant):
        QtWidgets.QFrame.__init__(self, parant)
        self.setupUi()

    def setupUi(self):
        self.setObjectName("Form")
        self.resize(396, 291)
        self.formLayoutWidget = QtWidgets.QWidget(self)
        self.formLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 301, 281))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.CBCashierPrinter = QtWidgets.QComboBox(self.formLayoutWidget)
        self.CBCashierPrinter.setObjectName("CBCashierPrinter")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.CBCashierPrinter)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.CBKitchenPrinter = QtWidgets.QComboBox(self.formLayoutWidget)
        self.CBKitchenPrinter.setObjectName("CBKitchenPrinter")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.CBKitchenPrinter)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "收银打印机"))
        self.label_2.setText(_translate("Form", "厨房打印机"))

    def SetupPrinters(self, Printer: PrinterControl):
        self.Printer = Printer
        self.PrintList = Printer.PrinterList()
        for PrinterName in self.PrintList:
            self.CBCashierPrinter.addItem(PrinterName)
        for PrinterName in self.PrintList:
            self.CBKitchenPrinter.addItem(PrinterName)
        self.CBCashierPrinter.setCurrentText(self.Printer.DefaultCashierPrinter)
        self.CBKitchenPrinter.setCurrentText(self.Printer.DefaultKitchenPrinter)
        print(self.Printer.DefaultCashierPrinter)
        print(self.Printer.DefaultKitchenPrinter)
        self.CBKitchenPrinter.currentIndexChanged.connect(self.KichenPrinterChange)
        self.CBCashierPrinter.currentIndexChanged.connect(self.CashierPrinterChange)

    def KichenPrinterChange(self, index):
        self.Printer.DefaultKitchenPrinter = self.PrintList[index]

    def CashierPrinterChange(self, index):
        self.Printer.DefaultCashierPrinter = self.PrintList[index]


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = SettingPanel(None)
    ui.setupUi()
    Form.show()
    sys.exit(app.exec_())
