# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui/Status.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class StatusPanel(QtWidgets.QFrame):
    def __init__(self, parant):
        QtWidgets.QFrame.__init__(self, parant)
        self.setupUi()
        self.TableNumber = None

    def setupUi(self):
        self.setObjectName("Form")
        self.resize(468, 232)
        self.formLayoutWidget = QtWidgets.QWidget(self)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 9, 281, 131))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.LBTableNumber = QtWidgets.QLabel(self.formLayoutWidget)
        self.LBTableNumber.setObjectName("LBTableNumber")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LBTableNumber)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.LBNumOfPeople = QtWidgets.QLabel(self.formLayoutWidget)
        self.LBNumOfPeople.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LBNumOfPeople.setObjectName("LBNumOfPeople")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LBNumOfPeople)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.LBStartTime = QtWidgets.QLabel(self.formLayoutWidget)
        self.LBStartTime.setObjectName("LBStartTime")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LBStartTime)
        self.gridLayoutWidget = QtWidgets.QWidget(self)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 150, 295, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.BtnCleanTable = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.BtnCleanTable.setObjectName("BtnCleanTable")
        self.gridLayout.addWidget(self.BtnCleanTable, 0, 1, 1, 1)
        self.BtnNewOrder = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.BtnNewOrder.setObjectName("BtnNewOrder")
        self.gridLayout.addWidget(self.BtnNewOrder, 0, 0, 1, 1)
        self.BtnCheckOut = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.BtnCheckOut.setObjectName("BtnCheckOut")
        self.gridLayout.addWidget(self.BtnCheckOut, 0, 2, 1, 1)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Status"))
        self.label.setText(_translate("Form", "桌号"))
        self.LBTableNumber.setText(_translate("Form", "None"))
        self.label_2.setText(_translate("Form", "人数"))
        self.LBNumOfPeople.setText(_translate("Form", "None"))
        self.label_3.setText(_translate("Form", "开始时间"))
        self.LBStartTime.setText(_translate("Form", "None"))
        self.BtnCleanTable.setText(_translate("Form", "关台"))
        self.BtnNewOrder.setText(_translate("Form", "下单"))
        self.BtnCheckOut.setText(_translate("Form", "结账"))

    def DisplayTable(self, TableInfo):
        self.LBTableNumber.setText(TableInfo.TableID)
        self.TableNumber = TableInfo.TableID
        self.LBStartTime.setText(TableInfo.StartTime)
        self.LBNumOfPeople.setText(str(TableInfo.NumOfPeople))

    def CloseTableConnect(self, Event):
        self.BtnCleanTable.pressed.connect(Event)

    def NewOrderConnect(self, Event):
        pass

    def CheckOutConnect(self, Event):
        pass

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ui = StatusPanel(None)
    ui.show()
    sys.exit(app.exec_())
